- name: Install Basic Packages
  hosts: localhost


  tasks:
    - name: Update apt cache and install core tools
      apt:
        name:
          - vim
          - nala
          - git
        state: present
        update_cache: yes
      become: true

    - name: Install Desktop Environment components
      apt:
        name:
          - xserver-xorg
          - i3
          - lightdm
        state: present
      become: true

    - name: Install Additional Utilities
      apt:
        name:
          - kitty
          - suckless-tools
        state: present
      become: true
    
    # --- Shell Aliases --- #
    - name: alias sudo to 'sudo ' in bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'alias sudo="sudo "'
        insertafter: EOF
        state: present

    - name: alias apt to 'nala' in bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'alias apt="nala"'
        insertafter: EOF
        state: present
