- name: Install Basic Packages
  hosts: localhost

# --- Install Basic Packages --- #
  tasks:
    - name: Update apt cache and install core tools
      apt:
        name:
          - vim
          - nala
          - git
          - default-jre
        state: present
        update_cache: yes
      become: true

    - name: Install Desktop Environment components
      apt:
        name:
          - xserver-xorg
          - i3
          - lightdm
        state: present
      become: true

    - name: Install Additional Utilities
      apt:
        name:
          - kitty
          - suckless-tools
        state: present
      become: true
    
    # --- End Install Basic Packages --- #

    # --- Shell Aliases --- #
    - name: alias sudo to 'sudo ' in bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'alias sudo="sudo "'
        insertafter: EOF
        state: present

    - name: alias apt to 'nala' in bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'alias apt="nala"'
        insertafter: EOF
        state: present

    # --- End Shell Aliases --- #

    # --- i3 Config --- #
    - name: Clone personal i3 config repo to temp location
      ansible.builtin.git:
        repo: https://github.com/lambo12000/i3_vms.git
        dest: /tmp/i3_vms
        clone: yes
        update: yes # Optional: pull latest changes if repo already cloned

    - name: Move i3 config folder to user config directory
      ansible.builtin.copy:
        src: /tmp/i3_vms/i3
        dest: "{{ ansible_user_dir }}/.config/"
        remote_src: yes
        directory_mode: preserve # Keeps original permissions

    - name: Remove temporary i3 config repo clone
      ansible.builtin.file:
        path: /tmp/i3_vms
        state: absent

    # --- End i3 Config --- #
