- name: Install Basic Packages
  hosts: localhost
  become: true


  tasks:
    - name: Update apt cache and install core tools
      apt:
        name:
          - nala
          - neovim
          - git
        state: present
        update_cache: yes

    - name: Install Desktop Environment components
      apt:
        name:
          - xserver-xorg
          - i3
          - lightdm
        state: present

    - name: Install Additional Utilities
      apt:
        name:
          - kitty
          - suckless-tools
        state: present

    - name: download lazyvim starter
      ansible.builtin.git:
        repo: https://github.com/LazyVim/starter
        dest: "{{ ansible_user_dir }}/.config/nvim"

    - name: remove the .git folder from lazyvim starter
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/nvim/.git"
        state: absent

    - name: alias sudo to 'sudo ' in bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'alias sudo="sudo "'
        insertafter: EOF
        state: present

    - name: alias apt to 'nala' in bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'alias apt="nala"'
        insertafter: EOF
        state: present