- name: Install Basic Packages
  hosts: localhost
  become: true

  #apt tasks
  tasks:
    - name: Install essential packages
      apt:
        name:
          - nala
          - neovim
          - git
          - xserver-xorg
          - i3
          - lightdm
          - kitty
          - suckless-tools
        state: present
        update_cache: yes # Update cache once before installing

    - name: download lazyvim starter
      ansible.builtin.git:
        repo: https://github.com/LazyVim/starter
        dest: "{{ ansible_user_dir }}/.config/nvim"