- name: Install Basic Packages
  hosts: localhost


  tasks:
    - name: Update apt cache and install core tools
      apt:
        name:
          - nala
          - neovim
          - git
        state: present
        update_cache: yes
      become: true

    - name: Install Desktop Environment components
      apt:
        name:
          - xserver-xorg
          - i3
          - lightdm
        state: present
      become: true

    - name: Install Additional Utilities
      apt:
        name:
          - kitty
          - suckless-tools
        state: present
      become: true
    
    - name: Check if nvim config directory exists
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.config/nvim"
      register: nvim_config_stat

    - name: download lazyvim starter
      ansible.builtin.git:
        repo: https://github.com/LazyVim/starter
        dest: "{{ ansible_user_dir }}/.config/nvim"
      when: not nvim_config_stat.stat.exists
      register: lazyvim_clone_result

    - name: remove the .git folder from lazyvim starter
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/nvim/.git"
        state: absent
      when: lazyvim_clone_result.changed

    - name: alias sudo to 'sudo ' in bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'alias sudo="sudo "'
        insertafter: EOF
        state: present

    - name: alias apt to 'nala' in bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'alias apt="nala"'
        insertafter: EOF
        state: present